/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark_Targets.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import gsap from "gsap";
import { useNavigate } from "react-router";

export default function Model(props) {
  let navigate = useNavigate();

  const { nodes: fanNodes } = useGLTF("/models/Dark Room/StandFan_Target.glb");

  const whiteMaterial = new THREE.MeshBasicMaterial({ 
    color: 0xffffff,
    transparent: true,
    opacity: 0
  });

  const aboutAnimRef = useRef();
  const devWorkAnimRef = useRef();
  const fanAnimRef = useRef();

  const animationPairs = {
    About_Hitbox: { ref: aboutAnimRef },
    Dev_Work_Hitbox: { ref: devWorkAnimRef },
    Fan_Hitbox: { ref: fanAnimRef }
  };

  //Handle Hover
  const onHover = (key, isHovering) => {
    const animObject = animationPairs[key];
    gsap.to(animObject.ref.current.material, {
      opacity: isHovering ? 1 : 0,
      duration: 0.5,
    });
  };

  return (
    <group {...props} dispose={null}>

      <mesh
        geometry={fanNodes.Stand_Fan_Hitbox.geometry}
        material={fanNodes.Stand_Fan_Hitbox.material}
        visible={false}
        position={[1.07, 0.817, 0.307]}
        rotation={[0, 0.932, 0]}
        scale={[0.413, 1.278, 0.557]}
        onPointerOver={() => {
          onHover("Fan_Hitbox", true);
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={() => {
          onHover("Fan_Hitbox", false);
          document.body.style.cursor = "auto";
        }}
        onClick={() => {
          navigate("/stand-fan-controls");
        }}
      />
      <mesh
        ref={fanAnimRef}
        geometry={fanNodes.Stand_Fan_HitBox_Anim.geometry}
        material={whiteMaterial}
        position={[1.189, 1.544, 0.828]}
        rotation={[0, 0.932, 0]}
        scale={[0.413, 1.278, 0.557]}
      />
    </group>
  );
}

useGLTF.preload("/models/Dark Room/StandFan_Target.glb");
