/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sandwichsoul (https://sketchfab.com/sandwichsoul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/room-867c25e5dd6145c7a219a9a7982ea492
Title: room
*/

import { useRef, useEffect } from "react";
import { useFrame, useThree } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";
import roomScene from "../assets/3d/room.glb";

const Room = ({ isRotating, setIsRotating, ...props }) => {
  const roomRef = useRef();
  const { scene, animations } = useGLTF(roomScene);

  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(roomScene);

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;

    lastX.current = clientX;
  };

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;

    const delta = (clientX - lastX.current) / viewport.width;
    roomRef.current.rotation.y += delta * 0.01 * Math.PI;
    lastX.current = clientX;
    rotationSpeed.current = delta * 0.01 * Math.PI;
  };

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const delta = (clientX - lastX.current) / viewport.width;
      roomRef.current.rotation.y += delta * 0.01 * Math.PI;
      lastX.current = clientX;
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === "ArrowLeft") {
      roomRef.current.rotation.y += 0.01 * Math.PI;
    } else if (e.key === "ArrowRight") {
      roomRef.current.rotation.y -= 0.01 * Math.PI;
    }
  };

  const handleKeyUp = (e) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      setIsRotating(false);
    }
  };

  useFrame(() => {
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }
      roomRef.current.rotation.y += rotationSpeed.current;
    }
  });

  useEffect(() => {
    document.addEventListener("pointerdown", handlePointerDown);
    document.addEventListener("pointerup", handlePointerUp);
    document.addEventListener("pointermove", handlePointerMove);
    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("keyup", handleKeyUp);

    return () => {
      document.removeEventListener("pointerdown", handlePointerDown);
      document.removeEventListener("pointerup", handlePointerUp);
      document.removeEventListener("pointermove", handlePointerMove);
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("keyup", handleKeyUp);
    };
  }, [isRotating]);

  return (
    <a.group ref={roomRef} {...props} dispose={null}>
      <group position={[-1, -1, 0]} rotation={[0, 0, 0]} scale={3}>
        <primitive object={nodes.Room || scene} />
      </group>
    </a.group>
  );
};

export default Room;
